backend:
  name: github
  repo: muneesmohammed333/mylogoworks   # 🔹 replace with your repo name
  branch: main                          # branch name

media_folder: "static/images/uploads"   # where uploaded images go in repo
public_folder: "/images/uploads"        # where images are served from

collections:
  - name: "pages"        # folder in repo
    label: "Pages"
    files:
      - file: "index.html"    # you can also point to Markdown if you want
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
